### ISSUE TITLE
orin nano image just constantly reboots

### ISSUE THREAD

**Issue by arrow53** [analogdevicesinc/gmsl#3]
the orin nano image just constantly reboots (I have console connected) and I never get a desktop screen. Any suggestions what could be wrong?

**Comment by fnsangiul** [comment]
@arrow53 how did you solve this issue?

**Comment by arrow53** [comment]
Make sure your bootloader version matches the image you're trying to load off the SD card.

**Comment by fnsangiul** [comment]
Thank you @arrow53. For anyone else encountering the same issue, simply flash JetPack 5.1.1 onto the SD card using the NVIDIA SDK. JetPack 5.1.1 is only compatible with Ubuntu 20.04, and from the nvidia forums you can't flash the SD using a virtual machine.
